run:
	go run ./main.go ./dbAccess.go ./handlers.go ./templating.go
	실행파일 webRoot으로 옮기고 서버 실행하기

test:
	go test ./main.go ./dbAccess.go ./handlers.go ./templating.go ./templating_test.go

back:
	go run ./main.go ./dbAccess.go ./handlers.go ./templating.go &


build:
	go build ./main.go ./dbAccess.go ./handlers.go ./templating.go
