run:
	go run ./main.go ./dbAccess.go ./handlers.go ./templating.go

test:
	go test ./main.go ./dbAccess.go ./handlers.go ./templating.go ./templating_test.go

back:
	go run ./main.go ./dbAccess.go ./handlers.go ./templating.go &


build:
	go build ./main.go ./dbAccess.go ./handlers.go ./templating.go
